namespace ExcelMcp.Bridge.Contracts;

public static class ToolNames
{
    public const string SessionListOpenWorkbooks = "session_list_open_workbooks";
    public const string SessionConnectWorkbook = "session_connect_workbook";
    public const string SessionCreateWorkbook = "session_create_workbook";
    public const string SessionListConnections = "session_list_connections";
    public const string SessionGetConnection = "session_get_connection";
    public const string SessionDisconnectWorkbook = "session_disconnect_workbook";
    public const string WorkbookSave = "workbook_save";
    public const string WorkbookSaveAs = "workbook_save_as";
    public const string WorkbookListInventory = "workbook_list_inventory";
    public const string WorkbookListNames = "workbook_list_names";
    public const string WorksheetCreate = "worksheet_create";
    public const string WorksheetRename = "worksheet_rename";
    public const string WorksheetDelete = "worksheet_delete";
    public const string WorksheetMove = "worksheet_move";
    public const string WorksheetCopy = "worksheet_copy";
    public const string WorksheetSetVisibility = "worksheet_set_visibility";
    public const string QueryGet = "query_get";
    public const string NameGet = "name_get";
    public const string NameRead = "name_read";
    public const string NameCreate = "name_create";
    public const string NameUpdate = "name_update";
    public const string NameDelete = "name_delete";
    public const string QueryRefresh = "query_refresh";
    public const string QueryRunProbe = "query_run_probe";
    public const string QueryCleanupTemp = "query_cleanup_temp";
    public const string QuerySetFormula = "query_set_formula";
    public const string TableGet = "table_get";
    public const string TableRead = "table_read";
    public const string TableCreate = "table_create";
    public const string TableResize = "table_resize";
    public const string TableAppendRows = "table_append_rows";
    public const string TableReplaceRows = "table_replace_rows";
    public const string TableDelete = "table_delete";
    public const string TableSetOptions = "table_set_options";
    public const string RangeRead = "range_read";
    public const string RangeWrite = "range_write";
    public const string RangeGetFormat = "range_get_format";
    public const string RangeSetFormat = "range_set_format";
    public const string RangeAutofit = "range_autofit";
    public const string RangeGetFormulas = "range_get_formulas";
    public const string RangeSetFormulas = "range_set_formulas";
    public const string RangeClear = "range_clear";
    public const string CalculationRecalculate = "calculation_recalculate";
    public const string CalculationInspectErrors = "calculation_inspect_errors";
    public const string SessionGrantMutationPermission = "session_grant_mutation_permission";
    public const string SessionRevokeMutationPermission = "session_revoke_mutation_permission";
    public const string SessionGetMutationPermission = "session_get_mutation_permission";
    public const string AttachedSessionGrantMutation = "attached_session_grant_mutation";
    public const string AttachedSessionRevokeMutation = "attached_session_revoke_mutation";
}
